name: Beacolanders
version: '${project.version}'
main: ua.favn.beacolanders.Beacolanders
api-version: '26.3'
author: favn
description: Server companion plugin for Beacoland

commands:
  beacolanders:
    description: Open the Beacolanders player menu
    aliases: [bl]
    usage: /<command>
